config/routes.rb
Rails.application.routes.draw do
root 'people#index'

resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

    def create
      @person = Person.new(person_params)
      if @person.save
        redirect_to people_path(@person)
      else
        render :new
      end
    end


  def edit
    @person = Person.find(params[:id])
  end



  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private
  
  def person_params
    params.require(:person).permit(:name, :age, :eye_color, :hair_color, :gender, :alive)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<h1>People</h1>
<hr />

<%= link_to 'New Entry', new_person_path %>

<% if @people.empty? %>
  <h3>Nothing to report...</h3>
  <% else %>
  <ul>
    <% @people.each do |people| %>
    <li>
      <%= link_to people.name, people_path(people) %>
      <%= link_to 'Delete', people_path(people), method: :delete %>
      <%= link_to 'Show Details', person_path(people) %>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/people/new.html.erb
<h1> Create New Entry </h1>
<hr />

<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :age %>
  <%= f.text_field :age %>
  <br />

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
  <br />

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
  <br />

  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br />

  <%= f.label :alive %>
  <%= f.text_field :alive %>
  <br />

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h2><%= @person.name %></h2>


<h3>Age</h3>
<%= @person.age%>
<br />

<h3>Eye color</h3>
<%= @person.eye_color%>
<br />

<h3>Hair Color</h3>
<%= @person.hair_color%>
<br />

<h3>Gender</h3>
<%= @person.gender%>
<br />

<h3>Alive</h3>
<%= @person.alive%>
<br />

<%= link_to 'People', people_path %>